[versions]
# Define the versions of your dependencies here
kotlin = "1.5.21"
coroutines = "1.5.0"
serialization = "1.2.2"

[plugins]
# Define the versions of your plugins here
androidGradlePlugin = "4.2.2"
kotlinGradlePlugin = "1.5.21"

