name: Build APK

on:
  repository_dispatch:
    types: [build_apk]  # This workflow can be triggered manually via a repository dispatch event

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Check out the repository code
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Set up JDK 17 for Android SDK tools (required for Android SDK Manager)
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Set the JDK version to 17

      # Step 3: Install Android SDK tools (command-line tools)
      - name: Install Android SDK tools
        run: |
          sudo apt update
          sudo apt install -y unzip wget
          
          # Download and install Android Command-line Tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          unzip commandlinetools-linux-8512546_latest.zip -d $HOME
          
          # Set up Android SDK paths
          mkdir -p $HOME/Android/cmdline-tools
          mv cmdline-tools $HOME/Android/cmdline-tools/latest
          
          # Set environment variables for Android SDK
          export ANDROID_HOME=$HOME/Android
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
          
          # Accept SDK licenses and install platform tools, build tools, and Android platforms
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "build-tools;30.0.3" "platforms;android-30"

      # Step 4: Set up Gradle
      - name: Install Gradle
        run: |
          wget https://services.gradle.org/distributions/gradle-7.4-bin.zip
          unzip gradle-7.4-bin.zip
          sudo mv gradle-7.4 /opt/gradle
          export PATH=$PATH:/opt/gradle/bin
          
          # Verify Gradle installation
          gradle -v

      # Step 5: Build the APK using Gradle
      - name: Build APK with Gradle
        run: |
          # Ensure gradlew is executable
          chmod +x gradlew
          
          # Build the release APK (you can modify this if you want to build a debug APK)
          ./gradlew assembleRelease

      # Step 6: Upload the APK as an artifact
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: apk-file
          path: app/build/outputs/apk/release/app-release.apk  # Path to the APK file
