name: Build APK
on:
  repository_dispatch:
    types: [build_apk]  # Triggered by manual repository dispatch (for example, API calls)

jobs:
  build:
    runs-on: ubuntu-latest  # The environment where the workflow will run

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  # Check out the repository code

      - name: Set up Java JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'  # Set the JDK version to 11

      - name: Set up Android SDK
        run: |
          sudo apt update
          sudo apt install -y unzip wget
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          unzip commandlinetools-linux-8512546_latest.zip -d $HOME
          mkdir -p $HOME/Android/cmdline-tools
          mv cmdline-tools $HOME/Android/cmdline-tools/latest
          yes | $HOME/Android/cmdline-tools/latest/bin/sdkmanager --licenses
          $HOME/Android/cmdline-tools/latest/bin/sdkmanager "platform-tools" "build-tools;30.0.3" "platforms;android-30"
        env:
          ANDROID_HOME: $HOME/Android  # Set ANDROID_HOME environment variable
          PATH: $HOME/Android/cmdline-tools/latest/bin:$PATH  # Add sdkmanager to the PATH

      - name: Ensure gradlew is executable
        run: chmod +x gradlew  # Make sure the Gradle wrapper is executable

      - name: Build APK with Gradle
        run: |
          # Check if gradlew exists and is executable
          ls -l ./gradlew
          ./gradlew assembleRelease  # Build the APK
          
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3  # Updated to v3 as v2 is deprecated
        with:
          name: apk-file
          path: app/build/outputs/apk/release/app-release.apk  # Path to the APK file

