name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04  # Use the latest Ubuntu version

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java JDK 17
        uses: actions/setup-java@2
        with:
          java-version: '17'
          distribution: 'adoptopenjdk'

      - name: Set JAVA_HOME
        run: echo "JAVA_HOME=/opt/hostedtoolcache/Java_Adopt_jdk/17.0.0/x64" >> $GITHUB_ENV

      - name: Install Android SDK
        run: |
          sudo apt update
          sudo apt install -y unzip wget
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          unzip commandlinetools-linux-8512546_latest.zip -d $HOME/android-sdk
          mkdir -p $HOME/android-sdk/cmdline-tools
          mv cmdline-tools $HOME/android-sdk/cmdline-tools/latest
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
          $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "build-tools;30.0.3" "platforms;android-30"

      - name: Build APK
        run: |
          # Change to your project directory
          cd android_project
          ./gradlew assembleRelease  # Or use assembleDebug for debugging

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: apk-artifact
          path: app/build/outputs/apk/release/app-release.apk
