name: Build APK

on:
  push:
    branches:
      - main  # Trigger workflow when pushing to the main branch
  workflow_dispatch:  # This allows the workflow to be triggered manually

jobs:
  build:
    runs-on: ubuntu-latest  # The environment where the workflow will run

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Set up Android SDK
        run: |
          sudo apt update
          sudo apt install -y unzip
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          unzip commandlinetools-linux-8512546_latest.zip
          mkdir -p $ANDROID_HOME/cmdline-tools
          mv cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "build-tools;30.0.3" "platforms;android-30"

      - name: Set up Gradle
        run: |
          wget https://services.gradle.org/distributions/gradle-6.7-bin.zip
          unzip gradle-6.7-bin.zip
          sudo mv gradle-6.7 /opt/gradle
          export PATH=$PATH:/opt/gradle/bin

      - name: Build APK
        run: ./gradlew assembleRelease  # Make sure your Gradle build file is in the root of the repo

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v2
        with:
          name: apk-file
          path: app/build/outputs/apk/release/app-release.apk
