name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adoptopenjdk'

      - name: Set up Android SDK
        run: |
          sudo apt update
          sudo apt install -y unzip
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          unzip commandlinetools-linux-8512546_latest.zip
          mkdir -p $ANDROID_HOME/cmdline-tools
          mv cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "build-tools;30.0.3" "platforms;android-30"

      - name: Set up Gradle
        run: |
          wget https://services.gradle.org/distributions/gradle-6.7-bin.zip
          unzip gradle-6.7-bin.zip
          sudo mv gradle-6.7 /opt/gradle
          export PATH=$PATH:/opt/gradle/bin

      - name: Build APK
        run: |
          mkdir -p android_project
          cd android_project
          gradle init --type basic
          
          # Modify build.gradle, app files, etc., to include WebView and the URL

          # Build the APK
          ./gradlew assembleRelease

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3  # Updated version to v3
        with:
          name: apk-file
          path: app/build/outputs/apk/release/app-release.apk
